spring.application.name=student-mgmt
spring.datasource.url=jdbc:mysql://localhost:3306/studentmgmt
spring.datasource.username=root
spring.datasource.password=Shravs@02
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
